import { Save, Trash2 } from "lucide-react";
import { artifactDownloadUrl } from "../api";
import { sourceFileName } from "../lib/format";
import type { ArtifactNode, ArtifactType, ArtifactValue, RunDetail, WorkflowEdge } from "../types";

type ArtifactInspectorProps = {
  artifactDraft: ArtifactNode | null;
  selectedArtifactProducer: WorkflowEdge | null;
  selectedArtifactProducerName: string;
  artifactApprovedRun: RunDetail | null;
  artifactApprovedValue: ArtifactValue | null;
  artifactPreviewText: string;
  artifactPreviewLoading: boolean;
  onSave: () => void;
  onDelete: () => void;
  onUpdateDraft: <K extends keyof ArtifactNode>(key: K, value: ArtifactNode[K]) => void;
  onUploadSourceFile: (file: File | null) => void;
};

export function ArtifactInspector({
  artifactDraft,
  selectedArtifactProducer,
  selectedArtifactProducerName,
  artifactApprovedRun,
  artifactApprovedValue,
  artifactPreviewText,
  artifactPreviewLoading,
  onSave,
  onDelete,
  onUpdateDraft,
  onUploadSourceFile
}: ArtifactInspectorProps) {
  if (!artifactDraft) {
    return null;
  }

  return (
    <>
      <div className="panel-title">
        <strong>Artifact</strong>
        <div className="button-cluster">
          <button className="icon-button" title="Save" onClick={onSave}>
            <Save size={16} />
          </button>
          <button className="icon-button danger" title="Delete" onClick={onDelete}>
            <Trash2 size={16} />
          </button>
        </div>
      </div>
      <label>
        Name
        <input value={artifactDraft.name} onChange={(event) => onUpdateDraft("name", event.target.value)} />
      </label>
      <label>
        Type
        <select
          value={artifactDraft.type}
          onChange={(event) => onUpdateDraft("type", event.target.value as ArtifactType)}
        >
          <option value="text">text</option>
          <option value="file">file</option>
          <option value="url">url</option>
        </select>
      </label>
      {selectedArtifactProducer && (
        <div className="field-block generated-source-note">
          <span>Source</span>
          <div className="muted-line">Generated by {selectedArtifactProducerName}. User source input is disabled.</div>
        </div>
      )}
      {!selectedArtifactProducer && artifactDraft.type === "text" && (
        <label>
          Source Text
          <textarea
            value={artifactDraft.source_text ?? ""}
            onChange={(event) => onUpdateDraft("source_text", event.target.value)}
            rows={7}
          />
        </label>
      )}
      {!selectedArtifactProducer && artifactDraft.type === "url" && (
        <label>
          Source URL
          <input
            value={artifactDraft.source_url ?? ""}
            onChange={(event) => onUpdateDraft("source_url", event.target.value)}
          />
        </label>
      )}
      {!selectedArtifactProducer && artifactDraft.type === "file" && (
        <div className="field-block">
          <span>Source File</span>
          <input type="file" onChange={(event) => onUploadSourceFile(event.target.files?.[0] ?? null)} />
          {artifactDraft.source_file_path ? (
            <div className="muted-line">Uploaded: {sourceFileName(artifactDraft.source_file_path)}</div>
          ) : (
            <div className="muted-line">No file uploaded.</div>
          )}
        </div>
      )}
      <div className="field-block">
        <span>Latest Approved Output</span>
        {!artifactApprovedRun && !artifactPreviewLoading && (
          <div className="muted-line">No approved output for this artifact yet.</div>
        )}
        {artifactPreviewLoading && <div className="muted-line">Loading approved output...</div>}
        {artifactApprovedRun && (
          <div className="artifact-row">
            <span>
              {artifactApprovedRun.id.slice(0, 12)} ({artifactApprovedRun.status})
            </span>
            {artifactApprovedValue?.artifact_type === "file" && (
              <a
                href={artifactDownloadUrl(artifactApprovedRun.id, artifactApprovedValue.artifact_id)}
                target="_blank"
                rel="noreferrer"
              >
                {artifactApprovedValue.file_path}
              </a>
            )}
            {artifactApprovedValue?.artifact_type === "url" && (
              <a href={artifactApprovedValue.url ?? ""} target="_blank" rel="noreferrer">
                {artifactApprovedValue.url}
              </a>
            )}
            {artifactApprovedValue?.artifact_type === "text" && (
              <textarea readOnly value={artifactPreviewText} rows={7} />
            )}
            {artifactApprovedValue?.artifact_type === "file" && (
              <textarea readOnly value={artifactPreviewText} rows={7} />
            )}
            {!artifactApprovedValue && (
              <div className="muted-line">The approved run has no value for this artifact.</div>
            )}
          </div>
        )}
      </div>
    </>
  );
}
