from __future__ import annotations

import asyncio
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

from agent_orchestrator.workspace import safe_name

from .base import AgentAdapter, AgentResult

if TYPE_CHECKING:
    from agent_orchestrator.execution import ExecutionEngine


class MockAgentAdapter(AgentAdapter):
    async def run(
        self,
        engine: ExecutionEngine,
        run: dict[str, Any],
        process: dict[str, Any],
        *,
        resume: bool,
        feedback_text: str,
    ) -> AgentResult:
        await engine._log(run["id"], "info", "Claude command was unavailable; using local mock adapter")
        await asyncio.sleep(0.05)
        workdir = Path(run["workdir_path"])
        output_yaml = workdir / "output" / "output.yaml"
        data = yaml.safe_load(output_yaml.read_text(encoding="utf-8")) or {"output": []}
        for item in data.get("output", []):
            name = item.get("name") or item.get("id") or "artifact"
            if item.get("type") == "file":
                rel = item.get("path") or f"output/{safe_name(name)}"
                target = workdir / rel
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(f"# {name}\n\nGenerated by the local mock adapter.\n", encoding="utf-8")
                item["path"] = rel
            elif item.get("type") == "url":
                item["url"] = item.get("url") or f"https://example.invalid/{safe_name(name)}"
            else:
                item["text"] = item.get("text") or f"Generated by the local mock adapter for {name}."
        output_yaml.write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=True), encoding="utf-8")
        await engine.record_usage(run["id"], process, input_tokens=1200, output_tokens=450)
        return AgentResult(ok=True, submitted=True, session_id=run.get("session_id") or f"mock-{run['id']}")
